
// Register Actions
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_ERROR_CLEAR = "REGISTER_ERROR_CLEAR";
export const REGISTER_RESPONSE = "REGISTER_RESPONSE";

// Login Actions
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_ERROR_CLEAR = "LOGIN_ERROR_CLEAR";
export const LOGIN_RESPONSE = "LOGIN_RESPONSE";
export const SET_LOGIN_USER = "SET_LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const UPDATE_PROFILE_PIC = "UPDATE_PROFILE_PIC";
