
// Register Actions
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_ERROR_CLEAR = "REGISTER_ERROR_CLEAR";
export const REGISTER_RESPONSE = "REGISTER_RESPONSE";
